spring:
  datasource:
    url: jdbc:mysql://localhost:3306/card
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to MyBank cards related APIs"
  contactDetails:
    email: "shivani@example.com"
    name: "Shivani - Product Owner"
  onCallSupport:
    - (+91) 7451247412
    - (+91) 5874285421
