server:
  port: 8085
spring:
  profiles:
    active:
      - "prod"
  application:
    name: cards
  datasource:
    url: jdbc:mysql://localhost:3306/card
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: "optional:configserver:http://localhost:8071/"

external:
  api:
    customer-service:
      url: http://localhost:8081
