server:
  port: 8085
spring:
  application:
    name: cards-service
  datasource:
    url: jdbc:mysql://localhost:3306/card
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect

external:
  api:
    customer-service:
      url: http://localhost:8081
