spring:
  application:
    name: customers
  profiles:
    active:
      - "prod"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customer
      username: root
      password: root
      authentication-database: admin
  config:
    import: "optional:configserver:http://localhost:8071/"
external:
  api:
    account-service:
      url: http://localhost:8082

server:
  port: 8081
