spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customer
      username: root
      password: root
      authentication-database: admin
  config:
    activate:
      on-profile: "qa"

build:
  version: "1.1"

customers:
  message: "Welcome to MyBank customer related APIs"
  contactDetails:
    email: "debabrata@example.com"
    name: "Debabrata - QA Lead"
  onCallSupport:
    - (+91) 7454712589
    - (+91) 7541284579