spring:
  config:
    import:
      - "application-qa.yml"
      - "application-prod.yml"
  profiles:
    active:
      - "qa"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customer
      username: root
      password: root
      authentication-database: admin

external:
  api:
    account-service:
      url: http://localhost:8082

server:
  port: 8081

build:
  version: "1.2"

customers:
  message: "Welcome to MyBank customer related APIs"
  contactDetails:
    email: "debashis@example.com"
    name: "Debashis - Developer"
  onCallSupport:
    - (+91) 7454712589
    - (+91) 7541284579