spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/account
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect


external:
  api:
    customer-service:
      url: http://localhost:8081


server:
  port: 8082

