spring:
  config:
    activate:
      on-profile: "qa"

  datasource:
    url: jdbc:mysql://localhost:3306/account
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect

build:
  version: "2.0"

accounts:
  message: "Welcome to MyBank accounts related APIs"
  contactDetails:
    email: "ayan@example.com"
    name: "Ayan - QA Lead"
  onCallSupport:
    - (+91) 4218754962
    - (+91) 3512634879

