server:
  port: 8084

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: transactions
      username: root
      password: root
      authentication-database: admin

external:
  api:
    customer-service:
      url: http://localhost:8081
    account-service:
      url: http://localhost:8082
    payment-service:
      url: http://localhost:8086
    loan-service:
      url: http://localhost:8083
    card-service:
      url: http://localhost:8085