spring:
    application:
        name: loan-service
    datasource:
        url: jdbc:mysql://localhost:3306/loan
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQLDialect
    profiles:
        active:
            - "prod"
    config:
        import:
            - "application-qa.yml"
            - "application-prod.yml"

external:
    api:
        customer-service:
            url: http://localhost:8081
        payment-service:
            url: http://localhost:8084

server:
    port: 8083

build:
    version: "1.2"

loans:
    message: "Welcome to MyBank loan related APIs"
    contactDetails:
        email: "debashis@example.com"
        name: "Debashis - Developer"
    onCallSupport:
        - (+91) 7454712589
        - (+91) 7541284579
