spring:
    datasource:
        url: jdbc:mysql://localhost:3306/loan
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQLDialect
    config:
        activate:
            on-profile: "prod"

build:
    version: "1.0"

loans:
    message: "Welcome to MyBank loan related APIs"
    contactDetails:
        email: "arijit@example.com"
        name: "Arijit - Product Owner"
    onCallSupport:
        - (+91) 8647512494
        - (+91) 9565523478
