spring:
    datasource:
        url: jdbc:mysql://localhost:3306/loan
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQLDialect
    config:
        activate:
            on-profile: "qa"

build:
    version: "1.1"

loans:
    message: "Welcome to MyBank loan related APIs"
    contactDetails:
        email: "hita@example.com"
        name: "Hitaishree - QA Lead"
    onCallSupport:
        - (+91) 7454745128
        - (+91) 8451279543
